name: CI'
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.17.0
    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      #  Run lint
      - name: Lint
        run: |
          npm run lint

      # - name: Test
      #   run: |
      #     npm run test

      - name: Build
        run: |
          npm run build
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: "${{ secrets.TOKEN_GITHUB_ACTION }}"
          preset: angular
          output-file: CHANGELOG.md
          skip-on-empty: "false"
